version: 2
jobs:
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
        environment:
          TZ: Asia/Tokyo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Print Android home
          command: echo $ANDROID_HOME
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Decode google-services.json
          command: echo $GOOGLE_SERVICE | base64 --decode > ./android/app/google-services.json
      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: cd android && ./gradlew test
      - run:
          name: Create jacoco report
          command: cd android && ./gradlew jacocoTestReport 
      - run:
          name: Publish to codecov
          command: cd android && bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: android/app/build/reports
          destination: reports
      - store_test_results:
          path: android/app/build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
  lint:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
        environment:
          TZ: Asia/Tokyo
    environment:
      JVM_OPTS: -Xmx1024m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Print Android home
          command: echo $ANDROID_HOME
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Decode google-services.json
          command: echo $GOOGLE_SERVICE | base64 --decode > ./android/app/google-services.json
      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies
      - run:
          name: Run lint for Google Play
          command: cd android && ./gradlew lintGooglePlayDebug
      - run:
          name: Run lint for non Google Play
          command: cd android && ./gradlew clean && ./gradlew lintNonGooglePlayDebug
      - store_artifacts:
          path: android/app/build/reports
          destination: reports
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - lint
