name: Android CI

on:
  pull_request:
    branches:
      - dev

jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE}}
        run: echo $GOOGLE_SERVICE | base64 --decode > ./app/google-services.json
      - name: Unit Test
        env:
          TZ: Asia/Tokyo
        run: ./gradlew testGooglePlayDebugUnitTest
      - name: Create jacoco report
        run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v3
        with:
          file: ./*/reports/jacoco/jacocoTestReport.xml

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE}}
        run: echo $GOOGLE_SERVICE | base64 --decode > ./app/google-services.json
      - name: Lint
        run: ./gradlew lintGooglePlayDebug
