name: Task for library update

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
      - dev
    paths:
      - 'android/gradle/libs.versions.toml'
      - 'android/build.gradle'

jobs:
  upload_dependency_list:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE}}
        run: echo $GOOGLE_SERVICE | base64 --decode > ./app/google-services.json
      - name: Create dependency list
        env:
          TZ: Asia/Tokyo
        run: ./gradlew app:dependencies > depend.txt
      - uses: actions/upload-artifact@v3
        with:
          name: Dependency list
          path: depend.txt

  dependency_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - id: dependency-diff
        name: Generate dependency diff
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          chmod +x scripts/dependency_diff.sh
          DIFF=$(scripts/dependency_diff.sh $BASE_BRANCH $BRANCH_NAME app releaseRuntimeClasspath)
          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "::set-output name=text-diff::${DIFF}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: peter-evans/find-comment@63281291b302e9cf92adff0e12a6f9d42c92a5e1
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff
      - uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
        if: ${{ steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Dependency diff:
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
